[build]
  base = "client"
  command = "npm ci && npm run build"
  publish = "dist"
  [build.environment]
    VITE_API_URL = "https://astral-back1-1.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://astral-back1-1.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
